// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AnnotationButton: typeof import("./components/AnnotationButton.vue")["default"];
    ImageDisplay: typeof import("./components/ImageDisplay.vue")["default"];
    LoginView: typeof import("./components/LoginView.vue")["default"];
    ProofOfCondition: typeof import("./components/ProofOfCondition.vue")["default"];
    TaskView: typeof import("./components/TaskView.vue")["default"];
    UserInformationLabel: typeof import("./components/UserInformationLabel.vue")["default"];
  }
}

export {};
