// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnnotationButton: typeof import('./components/AnnotationButton.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ImageDisplay: typeof import('./components/ImageDisplay.vue')['default']
    LoginView: typeof import('./components/LoginView.vue')['default']
    ProofOfCondition: typeof import('./components/ProofOfCondition.vue')['default']
    TaskView: typeof import('./components/TaskView.vue')['default']
    ToastNotification: typeof import('./components/ToastNotification.vue')['default']
    UserInformationLabel: typeof import('./components/UserInformationLabel.vue')['default']
  }
}

export {}
