[tool.isort]
profile = "black"

[tool.mypy]
disallow_untyped_defs = true
allow_redefinition = true
ignore_missing_imports = true
exclude = ["alembic"]

[tool.coverage.report]
omit = [ "mod/tests/*" ]
