name: Format static

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{js,ts}
