name: Format static

on:
  pull_request:
    branches:
      - main
      - dev

defaults:
  run:
    working-directory: static

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.repository }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: echo "nvmrc=$(cat .nvmrc)" >> $GITHUB_ENV
      - name: Use Node.js ${{ env.nvmrc }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.nvmrc }}
      - run: npm ci
      - run: npm run format
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automation: Code Formatter" --all | exit 0
          git push
