name: Generate REST Client

on:
  pull_request:
    branches:
      - main
      - dev

defaults:
  run:
    working-directory: static

jobs:
  generate-api:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.repository }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../api/requirements-dev.txt
      - run: echo "nvmrc=$(cat .nvmrc)" >> $GITHUB_ENV
      - name: Use Node.js ${{ env.nvmrc }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.nvmrc }}
      - name: Install node dependencies
        run: npm ci --no-save
      - name: API Generation
        run: npm run generate-aoi
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automation: REST Client Generator" --all | exit 0
          git push
